### ISSUE TITLE
ICN2053 auto refresh 

### ISSUE THREAD

**Issue by devRomeos** [LAutour/ESP32-HUB75-MatrixPanel-DMA-ICN2053#10]
I read a few years ago that this chip repeats the signals at the highest frequency (1920 / 3840 hz) on its own. So simply providing an image from 30fps onwards is more than enough for avoid flicker / black bar effects

Can anyone confirm if this is indeed correct and if this library acts in this way?

**Comment by lautour2** [comment]
Yes. The refresh rate of screen lines here does not depend in any way on the frame rate.
